### ISSUE TITLE
0.3.0 is not available on cargo

### ISSUE THREAD

**Issue by yoshuawuyts** [assert-rs/dir-diff#18]
dir-diff version: 0.3.0
rust version: 1.25.0-nightly
OS: Linux

---

The latest version on Cargo is `0.3.0`, but it's apparently not available. I'm not sure what to do about it, but maybe it was unpublished / something went wrong when deploying? `0.2.0` installs fine.

Maybe releasing a `0.4.0` might work so the latest version on cargo points to a valid release?

**Comment by epage** [comment]
I assume this is related to #10

**Comment by yoshuawuyts** [comment]
@epage ah yeah, that might be what I was seeing! I wasn't sure because https://docs.rs/dir-diff/0.3.0/dir_diff/ was also returning empty. Heaps odd hey.

**Comment by epage** [comment]
Looks like its fixed.  It looks right in the registry and docs.rs exists
https://docs.rs/dir-diff/0.3.1/dir_diff/
